[rospy.client][INFO] 2020-11-28 00:50:22,473: init_node, name[/train_10811_1606524622442], pid[10811]
[xmlrpc][INFO] 2020-11-28 00:50:22,474: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-11-28 00:50:22,474: Started XML-RPC server [http://192.168.0.191:38083/]
[rospy.init][INFO] 2020-11-28 00:50:22,474: ROS Slave URI: [http://192.168.0.191:38083/]
[rospy.impl.masterslave][INFO] 2020-11-28 00:50:22,475: _ready: http://192.168.0.191:38083/
[rospy.registration][INFO] 2020-11-28 00:50:22,476: Registering with master node http://192.168.0.201:11311
[xmlrpc][INFO] 2020-11-28 00:50:22,476: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2020-11-28 00:50:22,575: registered with master
[rospy.rosout][INFO] 2020-11-28 00:50:22,575: initializing /rosout core topic
[rospy.rosout][INFO] 2020-11-28 00:50:22,580: connected to core topic /rosout
[rospy.simtime][INFO] 2020-11-28 00:50:22,582: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2020-11-28 00:50:22,607: topic[/bev/flow_image] adding connection to [http://192.168.0.201:41889/], count 0
[rospy.internal][INFO] 2020-11-28 00:50:22,608: topic[/is_start_episode] adding connection to [http://192.168.0.201:46533/], count 0
[rospy.internal][INFO] 2020-11-28 00:50:22,610: topic[/scan] adding connection to [http://192.168.0.201:35871/], count 0
[rospy.internal][INFO] 2020-11-28 00:50:22,617: topic[/start_goal_points] adding connection to [http://192.168.0.201:33435/], count 0
[rospy.internal][INFO] 2020-11-28 00:50:22,619: topic[/scan] adding connection to [http://192.168.0.201:37851/], count 1
[rospy.internal][INFO] 2020-11-28 00:50:22,621: topic[/odom] adding connection to [http://192.168.0.201:37851/], count 0
[rospy.internal][INFO] 2020-11-28 00:50:22,624: topic[/bev/occupancy_image] adding connection to [http://192.168.0.201:41889/], count 0
[rospy.internal][INFO] 2020-11-28 00:50:22,862: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2020-11-28 00:50:22,868: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2020-11-28 00:50:22,869: topic[/cmd_vel] adding connection to [/bev_flow_estimator], count 1
[rospy.internal][INFO] 2020-11-28 00:50:22,872: topic[/episode_watcher/is_finish_episode] adding connection to [/episode_manager], count 0
[rospy.internal][WARNING] 2020-11-28 00:50:32,594: Unknown error initiating TCP/IP socket to 192.168.0.201:60111 (http://192.168.0.201:35871/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rosgraph/network.py", line 357, in read_ros_handshake_header
    d = sock.recv(buff_size)
ConnectionResetError: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2020-11-28 00:50:32,595: topic[/scan] removing connection to http://192.168.0.201:35871/
[rospy.internal][INFO] 2020-11-28 00:50:32,674: topic[/bev/flow_image] adding connection to [http://192.168.0.201:44441/], count 1
[rospy.internal][INFO] 2020-11-28 00:50:32,680: topic[/bev/occupancy_image] adding connection to [http://192.168.0.201:44441/], count 1
[rospy.internal][WARNING] 2020-11-28 00:50:32,681: Unknown error initiating TCP/IP socket to 192.168.0.201:35731 (http://192.168.0.201:41889/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rosgraph/network.py", line 357, in read_ros_handshake_header
    d = sock.recv(buff_size)
ConnectionResetError: [Errno 104] Connection reset by peer

[rospy.internal][WARNING] 2020-11-28 00:50:32,681: Unknown error initiating TCP/IP socket to 192.168.0.201:35731 (http://192.168.0.201:41889/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rosgraph/network.py", line 357, in read_ros_handshake_header
    d = sock.recv(buff_size)
ConnectionResetError: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2020-11-28 00:50:32,682: topic[/bev/flow_image] removing connection to http://192.168.0.201:41889/
[rospy.internal][INFO] 2020-11-28 00:50:32,682: topic[/bev/occupancy_image] removing connection to http://192.168.0.201:41889/
[rosout][WARNING] 2020-11-28 00:50:32,789: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[rospy.internal][WARNING] 2020-11-28 00:50:32,793: Unknown error initiating TCP/IP socket to 192.168.0.201:46983 (http://192.168.0.201:44441/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rosgraph/network.py", line 357, in read_ros_handshake_header
    d = sock.recv(buff_size)
ConnectionResetError: [Errno 104] Connection reset by peer

[rospy.internal][WARNING] 2020-11-28 00:50:32,794: Unknown error initiating TCP/IP socket to 192.168.0.201:46983 (http://192.168.0.201:44441/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rosgraph/network.py", line 357, in read_ros_handshake_header
    d = sock.recv(buff_size)
ConnectionResetError: [Errno 104] Connection reset by peer

[rospy.internal][ERROR] 2020-11-28 00:50:32,794: Inbound TCP/IP connection failed:
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 327, in _tcp_server_callback
    header = read_ros_handshake_header(sock, BytesIO(), buff_size)
  File "/opt/ros/noetic/lib/python3/dist-packages/rosgraph/network.py", line 359, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
rosgraph.network.ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2020-11-28 00:50:32,795: topic[/bev/occupancy_image] removing connection to http://192.168.0.201:44441/
[rospy.internal][INFO] 2020-11-28 00:50:32,795: topic[/bev/flow_image] removing connection to http://192.168.0.201:44441/
[rospy.internal][INFO] 2020-11-28 00:50:33,179: topic[/cmd_vel] removing connection to /bev_flow_estimator
[rospy.internal][INFO] 2020-11-28 00:50:36,022: topic[/bev/flow_image] adding connection to [http://192.168.0.201:34747/], count 0
[rospy.internal][INFO] 2020-11-28 00:50:36,027: topic[/bev/occupancy_image] adding connection to [http://192.168.0.201:34747/], count 0
[rospy.internal][INFO] 2020-11-28 00:50:36,121: topic[/cmd_vel] adding connection to [/bev_flow_estimator], count 1
[rospy.core][INFO] 2020-11-28 00:51:35,688: signal_shutdown [signal-2]
[rospy.internal][INFO] 2020-11-28 00:51:35,695: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-11-28 00:51:35,696: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2020-11-28 00:51:35,696: topic[/cmd_vel] removing connection to /bev_flow_estimator
[rospy.internal][INFO] 2020-11-28 00:51:35,696: topic[/episode_watcher/is_finish_episode] removing connection to /episode_manager
[rospy.internal][INFO] 2020-11-28 00:51:35,696: topic[/bev/flow_image] removing connection to http://192.168.0.201:34747/
[rospy.internal][INFO] 2020-11-28 00:51:35,697: topic[/bev/occupancy_image] removing connection to http://192.168.0.201:34747/
[rospy.internal][INFO] 2020-11-28 00:51:35,697: topic[/odom] removing connection to http://192.168.0.201:37851/
[rospy.internal][INFO] 2020-11-28 00:51:35,698: topic[/start_goal_points] removing connection to http://192.168.0.201:33435/
[rospy.internal][INFO] 2020-11-28 00:51:35,698: topic[/scan] removing connection to http://192.168.0.201:37851/
[rospy.internal][INFO] 2020-11-28 00:51:35,699: topic[/is_start_episode] removing connection to http://192.168.0.201:46533/
[rospy.internal][WARNING] 2020-11-28 00:51:35,699: Unknown error initiating TCP/IP socket to 192.168.0.201:44843 (http://192.168.0.201:37851/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.impl.masterslave][INFO] 2020-11-28 00:51:35,699: signal-2
[rospy.internal][WARNING] 2020-11-28 00:51:35,700: Unknown error initiating TCP/IP socket to 192.168.0.201:49431 (http://192.168.0.201:46533/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.core][INFO] 2020-11-28 00:51:36,190: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-28 00:51:36,233: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-28 00:51:36,253: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-28 00:51:36,284: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-28 00:51:36,340: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-28 00:51:36,353: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-28 00:51:36,363: signal_shutdown [atexit]
