[rospy.client][INFO] 2020-11-20 12:01:11,236: init_node, name[/train_1753_1605873671204], pid[1753]
[xmlrpc][INFO] 2020-11-20 12:01:11,237: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-11-20 12:01:11,238: Started XML-RPC server [http://192.168.0.191:46335/]
[rospy.init][INFO] 2020-11-20 12:01:11,238: ROS Slave URI: [http://192.168.0.191:46335/]
[rospy.impl.masterslave][INFO] 2020-11-20 12:01:11,238: _ready: http://192.168.0.191:46335/
[rospy.registration][INFO] 2020-11-20 12:01:11,240: Registering with master node http://192.168.0.201:11311
[xmlrpc][INFO] 2020-11-20 12:01:11,240: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2020-11-20 12:01:11,339: registered with master
[rospy.rosout][INFO] 2020-11-20 12:01:11,339: initializing /rosout core topic
[rospy.rosout][INFO] 2020-11-20 12:01:11,344: connected to core topic /rosout
[rospy.simtime][INFO] 2020-11-20 12:01:11,346: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2020-11-20 12:01:11,357: topic[/bev/flow_image] adding connection to [http://192.168.0.201:33717/], count 0
[rospy.internal][INFO] 2020-11-20 12:01:11,360: topic[/bev/occupancy_image] adding connection to [http://192.168.0.201:33717/], count 0
[rospy.internal][INFO] 2020-11-20 12:01:11,367: topic[/odom] adding connection to [http://192.168.0.201:37319/], count 0
[rospy.internal][INFO] 2020-11-20 12:01:11,375: topic[/scan] adding connection to [http://192.168.0.201:37319/], count 0
[rospy.internal][INFO] 2020-11-20 12:01:11,380: topic[/start_goal_points] adding connection to [http://192.168.0.201:33733/], count 0
[rospy.internal][INFO] 2020-11-20 12:01:11,381: topic[/scan] adding connection to [http://192.168.0.201:42031/], count 1
[rosout][ERROR] 2020-11-20 12:01:11,449: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f75ddcc31f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 150, in laser_callback
    print("msg.ranges = ", msg.ranges[i].data)
AttributeError: 'float' object has no attribute 'data'

[rosout][ERROR] 2020-11-20 12:01:11,478: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f75ddcc31f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 150, in laser_callback
    print("msg.ranges = ", msg.ranges[i].data)
AttributeError: 'float' object has no attribute 'data'

[rospy.internal][INFO] 2020-11-20 12:01:11,530: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2020-11-20 12:01:11,531: topic[/cmd_vel] adding connection to [/bev_flow_estimator], count 1
[rospy.internal][INFO] 2020-11-20 12:01:11,629: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2020-11-20 12:01:11,630: topic[/is_created_scenarios] adding connection to [/episode_manager], count 0
[rosout][ERROR] 2020-11-20 12:01:11,682: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f75ddcc31f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 150, in laser_callback
    print("msg.ranges = ", msg.ranges[i].data)
AttributeError: 'float' object has no attribute 'data'

[rosout][ERROR] 2020-11-20 12:01:11,715: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f75ddcc31f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 150, in laser_callback
    print("msg.ranges = ", msg.ranges[i].data)
AttributeError: 'float' object has no attribute 'data'

[rosout][ERROR] 2020-11-20 12:01:11,917: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f75ddcc31f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 150, in laser_callback
    print("msg.ranges = ", msg.ranges[i].data)
AttributeError: 'float' object has no attribute 'data'

[rosout][ERROR] 2020-11-20 12:01:11,946: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f75ddcc31f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 150, in laser_callback
    print("msg.ranges = ", msg.ranges[i].data)
AttributeError: 'float' object has no attribute 'data'

[rosout][ERROR] 2020-11-20 12:01:12,151: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f75ddcc31f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 150, in laser_callback
    print("msg.ranges = ", msg.ranges[i].data)
AttributeError: 'float' object has no attribute 'data'

[rosout][ERROR] 2020-11-20 12:01:12,180: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f75ddcc31f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 150, in laser_callback
    print("msg.ranges = ", msg.ranges[i].data)
AttributeError: 'float' object has no attribute 'data'

[rosout][ERROR] 2020-11-20 12:01:12,388: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f75ddcc31f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 150, in laser_callback
    print("msg.ranges = ", msg.ranges[i].data)
AttributeError: 'float' object has no attribute 'data'

[rosout][ERROR] 2020-11-20 12:01:12,421: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f75ddcc31f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 150, in laser_callback
    print("msg.ranges = ", msg.ranges[i].data)
AttributeError: 'float' object has no attribute 'data'

[rosout][ERROR] 2020-11-20 12:01:12,626: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f75ddcc31f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 150, in laser_callback
    print("msg.ranges = ", msg.ranges[i].data)
AttributeError: 'float' object has no attribute 'data'

[rosout][ERROR] 2020-11-20 12:01:12,659: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f75ddcc31f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 150, in laser_callback
    print("msg.ranges = ", msg.ranges[i].data)
AttributeError: 'float' object has no attribute 'data'

[rosout][ERROR] 2020-11-20 12:01:12,863: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f75ddcc31f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 150, in laser_callback
    print("msg.ranges = ", msg.ranges[i].data)
AttributeError: 'float' object has no attribute 'data'

[rosout][ERROR] 2020-11-20 12:01:12,895: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f75ddcc31f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 150, in laser_callback
    print("msg.ranges = ", msg.ranges[i].data)
AttributeError: 'float' object has no attribute 'data'

[rosout][ERROR] 2020-11-20 12:01:13,096: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f75ddcc31f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 150, in laser_callback
    print("msg.ranges = ", msg.ranges[i].data)
AttributeError: 'float' object has no attribute 'data'

[rosout][ERROR] 2020-11-20 12:01:13,128: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f75ddcc31f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 150, in laser_callback
    print("msg.ranges = ", msg.ranges[i].data)
AttributeError: 'float' object has no attribute 'data'

[rosout][ERROR] 2020-11-20 12:01:13,331: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f75ddcc31f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 150, in laser_callback
    print("msg.ranges = ", msg.ranges[i].data)
AttributeError: 'float' object has no attribute 'data'

[rosout][ERROR] 2020-11-20 12:01:13,361: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f75ddcc31f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 150, in laser_callback
    print("msg.ranges = ", msg.ranges[i].data)
AttributeError: 'float' object has no attribute 'data'

[rosout][ERROR] 2020-11-20 12:01:13,557: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f75ddcc31f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 150, in laser_callback
    print("msg.ranges = ", msg.ranges[i].data)
AttributeError: 'float' object has no attribute 'data'

[rosout][ERROR] 2020-11-20 12:01:13,582: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f75ddcc31f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 150, in laser_callback
    print("msg.ranges = ", msg.ranges[i].data)
AttributeError: 'float' object has no attribute 'data'

[rospy.core][INFO] 2020-11-20 12:01:13,759: signal_shutdown [signal-2]
[rospy.internal][INFO] 2020-11-20 12:01:13,763: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-11-20 12:01:13,763: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2020-11-20 12:01:13,763: topic[/cmd_vel] removing connection to /bev_flow_estimator
[rospy.internal][INFO] 2020-11-20 12:01:13,764: topic[/is_created_scenarios] removing connection to /episode_manager
[rospy.internal][INFO] 2020-11-20 12:01:13,764: topic[/bev/flow_image] removing connection to http://192.168.0.201:33717/
[rospy.internal][INFO] 2020-11-20 12:01:13,764: topic[/bev/occupancy_image] removing connection to http://192.168.0.201:33717/
[rospy.internal][INFO] 2020-11-20 12:01:13,765: topic[/odom] removing connection to http://192.168.0.201:37319/
[rospy.internal][INFO] 2020-11-20 12:01:13,765: topic[/start_goal_points] removing connection to http://192.168.0.201:33733/
[rospy.internal][INFO] 2020-11-20 12:01:13,766: topic[/scan] removing connection to http://192.168.0.201:37319/
[rospy.internal][INFO] 2020-11-20 12:01:13,766: topic[/scan] removing connection to http://192.168.0.201:42031/
[rospy.impl.masterslave][INFO] 2020-11-20 12:01:13,766: signal-2
[rospy.internal][WARNING] 2020-11-20 12:01:13,767: Unknown error initiating TCP/IP socket to 192.168.0.201:46553 (http://192.168.0.201:33717/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][WARNING] 2020-11-20 12:01:13,768: Unknown error initiating TCP/IP socket to 192.168.0.201:46553 (http://192.168.0.201:33717/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][WARNING] 2020-11-20 12:01:13,769: Unknown error initiating TCP/IP socket to 192.168.0.201:54625 (http://192.168.0.201:37319/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.core][INFO] 2020-11-20 12:01:13,789: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-20 12:01:13,820: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-20 12:01:13,853: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-20 12:01:13,881: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-20 12:01:13,912: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-20 12:01:13,945: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-20 12:01:13,979: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-20 12:01:14,021: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-20 12:01:14,040: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-20 12:01:14,070: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-20 12:01:14,112: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-20 12:01:14,136: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-20 12:01:14,204: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-20 12:01:14,248: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-20 12:01:14,266: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-20 12:01:14,297: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-20 12:01:14,335: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-20 12:01:14,413: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-20 12:01:14,427: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-20 12:01:14,478: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-20 12:01:14,491: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-20 12:01:14,492: signal_shutdown [atexit]
