[rospy.client][INFO] 2020-11-27 10:16:27,392: init_node, name[/train_8907_1606472187365], pid[8907]
[xmlrpc][INFO] 2020-11-27 10:16:27,393: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-11-27 10:16:27,394: Started XML-RPC server [http://192.168.0.191:38049/]
[rospy.init][INFO] 2020-11-27 10:16:27,394: ROS Slave URI: [http://192.168.0.191:38049/]
[rospy.impl.masterslave][INFO] 2020-11-27 10:16:27,394: _ready: http://192.168.0.191:38049/
[rospy.registration][INFO] 2020-11-27 10:16:27,395: Registering with master node http://192.168.0.201:11311
[xmlrpc][INFO] 2020-11-27 10:16:27,396: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2020-11-27 10:16:27,494: registered with master
[rospy.rosout][INFO] 2020-11-27 10:16:27,495: initializing /rosout core topic
[rospy.rosout][INFO] 2020-11-27 10:16:27,500: connected to core topic /rosout
[rospy.simtime][INFO] 2020-11-27 10:16:27,501: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2020-11-27 10:16:27,530: topic[/bev/flow_image] adding connection to [http://192.168.0.201:38319/], count 0
[rospy.internal][INFO] 2020-11-27 10:16:27,536: topic[/is_start_episode] adding connection to [http://192.168.0.201:34163/], count 0
[rospy.internal][INFO] 2020-11-27 10:16:27,537: topic[/scan] adding connection to [http://192.168.0.201:37211/], count 0
[rospy.internal][INFO] 2020-11-27 10:16:27,542: topic[/scan] adding connection to [http://192.168.0.201:38047/], count 1
[rospy.internal][INFO] 2020-11-27 10:16:27,545: topic[/start_goal_points] adding connection to [http://192.168.0.201:33229/], count 0
[rospy.internal][INFO] 2020-11-27 10:16:27,547: topic[/odom] adding connection to [http://192.168.0.201:38047/], count 0
[rospy.internal][INFO] 2020-11-27 10:16:27,549: topic[/bev/occupancy_image] adding connection to [http://192.168.0.201:38319/], count 0
[rospy.internal][INFO] 2020-11-27 10:16:27,711: topic[/cmd_vel] adding connection to [/bev_flow_estimator], count 0
[rospy.internal][INFO] 2020-11-27 10:16:27,713: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2020-11-27 10:16:27,814: topic[/episode_watcher/is_finish_episode] adding connection to [/episode_manager], count 0
[rospy.internal][INFO] 2020-11-27 10:16:27,815: topic[/cmd_vel] adding connection to [/gazebo], count 1
[rospy.internal][WARNING] 2020-11-27 10:16:35,129: Unknown error initiating TCP/IP socket to 192.168.0.201:52707 (http://192.168.0.201:37211/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rosgraph/network.py", line 357, in read_ros_handshake_header
    d = sock.recv(buff_size)
ConnectionResetError: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2020-11-27 10:16:35,129: topic[/scan] removing connection to http://192.168.0.201:37211/
[rospy.internal][INFO] 2020-11-27 10:16:35,182: topic[/bev/flow_image] adding connection to [http://192.168.0.201:40459/], count 1
[rospy.internal][INFO] 2020-11-27 10:16:35,187: topic[/bev/occupancy_image] adding connection to [http://192.168.0.201:40459/], count 1
[rospy.internal][INFO] 2020-11-27 10:16:35,191: topic[/scan] adding connection to [http://192.168.0.201:46023/], count 1
[rospy.internal][ERROR] 2020-11-27 10:16:35,194: Unable to initiate TCP/IP socket to 192.168.0.201:60389 (http://192.168.0.201:46023/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
rospy.exceptions.TransportInitError: remote error reported: received a connection for a nonexistent topic [/scan] from [TCPROS connection on port 60389 to [192.168.0.191:35538 on socket 11]] [/train_8907_1606472187365].

[rospy.internal][ERROR] 2020-11-27 10:16:35,194: unable to create subscriber transport: remote error reported: received a connection for a nonexistent topic [/scan] from [TCPROS connection on port 60389 to [192.168.0.191:35538 on socket 11]] [/train_8907_1606472187365]..  Will try again in 0.5s
[rospy.internal][WARNING] 2020-11-27 10:16:35,214: Unknown error initiating TCP/IP socket to 192.168.0.201:45293 (http://192.168.0.201:38319/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rosgraph/network.py", line 357, in read_ros_handshake_header
    d = sock.recv(buff_size)
ConnectionResetError: [Errno 104] Connection reset by peer

[rospy.internal][WARNING] 2020-11-27 10:16:35,214: Unknown error initiating TCP/IP socket to 192.168.0.201:45293 (http://192.168.0.201:38319/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rosgraph/network.py", line 357, in read_ros_handshake_header
    d = sock.recv(buff_size)
ConnectionResetError: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2020-11-27 10:16:35,215: topic[/bev/occupancy_image] removing connection to http://192.168.0.201:38319/
[rospy.internal][INFO] 2020-11-27 10:16:35,215: topic[/bev/flow_image] removing connection to http://192.168.0.201:38319/
[rospy.internal][WARNING] 2020-11-27 10:16:35,321: Unknown error initiating TCP/IP socket to 192.168.0.201:44667 (http://192.168.0.201:40459/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rosgraph/network.py", line 357, in read_ros_handshake_header
    d = sock.recv(buff_size)
ConnectionResetError: [Errno 104] Connection reset by peer

[rospy.internal][WARNING] 2020-11-27 10:16:35,321: Unknown error initiating TCP/IP socket to 192.168.0.201:44667 (http://192.168.0.201:40459/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rosgraph/network.py", line 357, in read_ros_handshake_header
    d = sock.recv(buff_size)
ConnectionResetError: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2020-11-27 10:16:35,321: topic[/bev/flow_image] removing connection to http://192.168.0.201:40459/
[rospy.internal][INFO] 2020-11-27 10:16:35,322: topic[/bev/occupancy_image] removing connection to http://192.168.0.201:40459/
[rospy.internal][INFO] 2020-11-27 10:16:35,694: topic[/cmd_vel] removing connection to /bev_flow_estimator
[rospy.internal][INFO] 2020-11-27 10:16:38,426: topic[/bev/flow_image] adding connection to [http://192.168.0.201:43751/], count 0
[rospy.internal][INFO] 2020-11-27 10:16:38,435: topic[/bev/occupancy_image] adding connection to [http://192.168.0.201:43751/], count 0
[rospy.internal][INFO] 2020-11-27 10:16:38,527: topic[/cmd_vel] adding connection to [/bev_flow_estimator], count 1
[rospy.internal][WARNING] 2020-11-27 10:17:15,977: Unknown error initiating TCP/IP socket to 192.168.0.201:41601 (http://192.168.0.201:34163/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rosgraph/network.py", line 357, in read_ros_handshake_header
    d = sock.recv(buff_size)
ConnectionResetError: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2020-11-27 10:17:15,977: topic[/is_start_episode] removing connection to http://192.168.0.201:34163/
[rospy.internal][WARNING] 2020-11-27 10:17:16,108: Unknown error initiating TCP/IP socket to 192.168.0.201:35115 (http://192.168.0.201:33229/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rosgraph/network.py", line 357, in read_ros_handshake_header
    d = sock.recv(buff_size)
ConnectionResetError: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2020-11-27 10:17:16,108: topic[/start_goal_points] removing connection to http://192.168.0.201:33229/
[rospy.internal][WARNING] 2020-11-27 10:17:16,226: Unknown error initiating TCP/IP socket to 192.168.0.201:45387 (http://192.168.0.201:43751/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rosgraph/network.py", line 357, in read_ros_handshake_header
    d = sock.recv(buff_size)
ConnectionResetError: [Errno 104] Connection reset by peer

[rospy.internal][WARNING] 2020-11-27 10:17:16,227: Unknown error initiating TCP/IP socket to 192.168.0.201:45387 (http://192.168.0.201:43751/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rosgraph/network.py", line 357, in read_ros_handshake_header
    d = sock.recv(buff_size)
ConnectionResetError: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2020-11-27 10:17:16,227: topic[/bev/occupancy_image] removing connection to http://192.168.0.201:43751/
[rospy.internal][INFO] 2020-11-27 10:17:16,227: topic[/bev/flow_image] removing connection to http://192.168.0.201:43751/
[rospy.internal][WARNING] 2020-11-27 10:17:16,280: Unknown error initiating TCP/IP socket to 192.168.0.201:44423 (http://192.168.0.201:38047/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rosgraph/network.py", line 357, in read_ros_handshake_header
    d = sock.recv(buff_size)
ConnectionResetError: [Errno 104] Connection reset by peer

[rospy.internal][WARNING] 2020-11-27 10:17:16,281: Unknown error initiating TCP/IP socket to 192.168.0.201:44423 (http://192.168.0.201:38047/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rosgraph/network.py", line 357, in read_ros_handshake_header
    d = sock.recv(buff_size)
ConnectionResetError: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2020-11-27 10:17:16,281: topic[/odom] removing connection to http://192.168.0.201:38047/
[rospy.internal][INFO] 2020-11-27 10:17:16,281: topic[/scan] removing connection to http://192.168.0.201:38047/
[rospy.internal][INFO] 2020-11-27 10:17:16,449: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2020-11-27 10:17:16,449: topic[/cmd_vel] removing connection to /bev_flow_estimator
[rospy.internal][INFO] 2020-11-27 10:17:16,450: topic[/episode_watcher/is_finish_episode] removing connection to /episode_manager
[rospy.core][INFO] 2020-11-27 10:17:21,385: signal_shutdown [signal-2]
[rospy.internal][INFO] 2020-11-27 10:17:21,395: topic[/rosout] removing connection to /rosout
[rospy.impl.masterslave][INFO] 2020-11-27 10:17:21,395: signal-2
[rospy.core][INFO] 2020-11-27 10:17:21,423: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-27 10:17:21,449: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-27 10:17:21,480: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-27 10:17:21,510: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-27 10:17:21,543: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-27 10:17:21,580: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-27 10:17:21,601: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-27 10:17:21,632: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-27 10:17:21,662: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-27 10:17:21,693: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-27 10:17:21,724: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-27 10:17:21,754: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-27 10:17:21,784: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-27 10:17:21,817: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-27 10:17:21,846: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-27 10:17:21,880: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-27 10:17:21,910: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-27 10:17:21,940: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-27 10:17:22,067: signal_shutdown [atexit]
