[rospy.client][INFO] 2020-11-24 04:06:46,449: init_node, name[/train_3530_1606190806417], pid[3530]
[xmlrpc][INFO] 2020-11-24 04:06:46,450: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-11-24 04:06:46,451: Started XML-RPC server [http://192.168.0.191:44785/]
[rospy.init][INFO] 2020-11-24 04:06:46,451: ROS Slave URI: [http://192.168.0.191:44785/]
[rospy.impl.masterslave][INFO] 2020-11-24 04:06:46,451: _ready: http://192.168.0.191:44785/
[rospy.registration][INFO] 2020-11-24 04:06:46,453: Registering with master node http://192.168.0.201:11311
[xmlrpc][INFO] 2020-11-24 04:06:46,453: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2020-11-24 04:06:46,552: registered with master
[rospy.rosout][INFO] 2020-11-24 04:06:46,552: initializing /rosout core topic
[rospy.rosout][INFO] 2020-11-24 04:06:46,558: connected to core topic /rosout
[rospy.simtime][INFO] 2020-11-24 04:06:46,559: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2020-11-24 04:06:46,578: topic[/bev/flow_image] adding connection to [http://192.168.0.201:45935/], count 0
[rospy.internal][INFO] 2020-11-24 04:06:46,589: topic[/scan] adding connection to [http://192.168.0.201:41579/], count 0
[rospy.internal][INFO] 2020-11-24 04:06:46,591: topic[/start_goal_points] adding connection to [http://192.168.0.201:40621/], count 0
[rospy.internal][INFO] 2020-11-24 04:06:46,592: topic[/scan] adding connection to [http://192.168.0.201:38893/], count 1
[rospy.internal][INFO] 2020-11-24 04:06:46,594: topic[/odom] adding connection to [http://192.168.0.201:41579/], count 0
[rospy.internal][INFO] 2020-11-24 04:06:46,595: topic[/bev/occupancy_image] adding connection to [http://192.168.0.201:45935/], count 0
[rospy.internal][INFO] 2020-11-24 04:06:46,753: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2020-11-24 04:06:46,754: topic[/cmd_vel] adding connection to [/bev_flow_estimator], count 1
[rosout][ERROR] 2020-11-24 04:06:46,777: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f53c68d01f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    self.scan_data = append(msg.ranges[i])
NameError: name 'append' is not defined

[rosout][ERROR] 2020-11-24 04:06:46,803: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f53c68d01f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    self.scan_data = append(msg.ranges[i])
NameError: name 'append' is not defined

[rospy.internal][INFO] 2020-11-24 04:06:46,852: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2020-11-24 04:06:46,854: topic[/is_created_scenarios] adding connection to [/episode_manager], count 0
[rosout][ERROR] 2020-11-24 04:06:47,003: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f53c68d01f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    self.scan_data = append(msg.ranges[i])
NameError: name 'append' is not defined

[rosout][ERROR] 2020-11-24 04:06:47,023: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f53c68d01f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    self.scan_data = append(msg.ranges[i])
NameError: name 'append' is not defined

[rosout][ERROR] 2020-11-24 04:06:47,229: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f53c68d01f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    self.scan_data = append(msg.ranges[i])
NameError: name 'append' is not defined

[rosout][ERROR] 2020-11-24 04:06:47,259: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f53c68d01f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    self.scan_data = append(msg.ranges[i])
NameError: name 'append' is not defined

[rosout][ERROR] 2020-11-24 04:06:47,461: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f53c68d01f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    self.scan_data = append(msg.ranges[i])
NameError: name 'append' is not defined

[rosout][ERROR] 2020-11-24 04:06:47,488: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f53c68d01f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    self.scan_data = append(msg.ranges[i])
NameError: name 'append' is not defined

[rosout][ERROR] 2020-11-24 04:06:47,686: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f53c68d01f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    self.scan_data = append(msg.ranges[i])
NameError: name 'append' is not defined

[rosout][ERROR] 2020-11-24 04:06:47,714: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f53c68d01f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    self.scan_data = append(msg.ranges[i])
NameError: name 'append' is not defined

[rosout][ERROR] 2020-11-24 04:06:47,915: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f53c68d01f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    self.scan_data = append(msg.ranges[i])
NameError: name 'append' is not defined

[rosout][ERROR] 2020-11-24 04:06:47,949: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f53c68d01f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    self.scan_data = append(msg.ranges[i])
NameError: name 'append' is not defined

[rosout][ERROR] 2020-11-24 04:06:48,150: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f53c68d01f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    self.scan_data = append(msg.ranges[i])
NameError: name 'append' is not defined

[rosout][ERROR] 2020-11-24 04:06:48,183: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f53c68d01f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    self.scan_data = append(msg.ranges[i])
NameError: name 'append' is not defined

[rosout][ERROR] 2020-11-24 04:06:48,385: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f53c68d01f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    self.scan_data = append(msg.ranges[i])
NameError: name 'append' is not defined

[rosout][ERROR] 2020-11-24 04:06:48,417: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f53c68d01f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    self.scan_data = append(msg.ranges[i])
NameError: name 'append' is not defined

[rosout][ERROR] 2020-11-24 04:06:48,616: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f53c68d01f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    self.scan_data = append(msg.ranges[i])
NameError: name 'append' is not defined

[rosout][ERROR] 2020-11-24 04:06:48,642: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f53c68d01f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    self.scan_data = append(msg.ranges[i])
NameError: name 'append' is not defined

[rosout][ERROR] 2020-11-24 04:06:48,840: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f53c68d01f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    self.scan_data = append(msg.ranges[i])
NameError: name 'append' is not defined

[rosout][ERROR] 2020-11-24 04:06:48,863: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f53c68d01f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    self.scan_data = append(msg.ranges[i])
NameError: name 'append' is not defined

[rosout][ERROR] 2020-11-24 04:06:49,059: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f53c68d01f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    self.scan_data = append(msg.ranges[i])
NameError: name 'append' is not defined

[rosout][ERROR] 2020-11-24 04:06:49,081: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f53c68d01f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    self.scan_data = append(msg.ranges[i])
NameError: name 'append' is not defined

[rosout][ERROR] 2020-11-24 04:06:49,280: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f53c68d01f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    self.scan_data = append(msg.ranges[i])
NameError: name 'append' is not defined

[rosout][ERROR] 2020-11-24 04:06:49,305: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f53c68d01f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    self.scan_data = append(msg.ranges[i])
NameError: name 'append' is not defined

[rosout][ERROR] 2020-11-24 04:06:49,503: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f53c68d01f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    self.scan_data = append(msg.ranges[i])
NameError: name 'append' is not defined

[rosout][ERROR] 2020-11-24 04:06:49,536: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f53c68d01f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    self.scan_data = append(msg.ranges[i])
NameError: name 'append' is not defined

[rosout][ERROR] 2020-11-24 04:06:49,736: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f53c68d01f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    self.scan_data = append(msg.ranges[i])
NameError: name 'append' is not defined

[rosout][ERROR] 2020-11-24 04:06:49,764: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f53c68d01f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    self.scan_data = append(msg.ranges[i])
NameError: name 'append' is not defined

[rosout][ERROR] 2020-11-24 04:06:49,968: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f53c68d01f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    self.scan_data = append(msg.ranges[i])
NameError: name 'append' is not defined

[rosout][ERROR] 2020-11-24 04:06:49,995: bad callback: <bound method ROSNode.laser_callback of <__main__.ROSNode object at 0x7f53c68d01f0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./train.py", line 151, in laser_callback
    self.scan_data = append(msg.ranges[i])
NameError: name 'append' is not defined

[rospy.core][INFO] 2020-11-24 04:06:50,098: signal_shutdown [signal-2]
[rospy.internal][INFO] 2020-11-24 04:06:50,103: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-11-24 04:06:50,103: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2020-11-24 04:06:50,104: topic[/cmd_vel] removing connection to /bev_flow_estimator
[rospy.internal][INFO] 2020-11-24 04:06:50,104: topic[/is_created_scenarios] removing connection to /episode_manager
[rospy.internal][INFO] 2020-11-24 04:06:50,104: topic[/bev/flow_image] removing connection to http://192.168.0.201:45935/
[rospy.internal][INFO] 2020-11-24 04:06:50,105: topic[/bev/occupancy_image] removing connection to http://192.168.0.201:45935/
[rospy.internal][INFO] 2020-11-24 04:06:50,105: topic[/odom] removing connection to http://192.168.0.201:41579/
[rospy.internal][INFO] 2020-11-24 04:06:50,106: topic[/start_goal_points] removing connection to http://192.168.0.201:40621/
[rospy.internal][INFO] 2020-11-24 04:06:50,106: topic[/scan] removing connection to http://192.168.0.201:41579/
[rospy.internal][INFO] 2020-11-24 04:06:50,107: topic[/scan] removing connection to http://192.168.0.201:38893/
[rospy.impl.masterslave][INFO] 2020-11-24 04:06:50,108: signal-2
[rospy.internal][WARNING] 2020-11-24 04:06:50,108: Unknown error initiating TCP/IP socket to 192.168.0.201:45977 (http://192.168.0.201:45935/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][WARNING] 2020-11-24 04:06:50,109: Unknown error initiating TCP/IP socket to 192.168.0.201:57717 (http://192.168.0.201:40621/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][WARNING] 2020-11-24 04:06:50,109: Unknown error initiating TCP/IP socket to 192.168.0.201:53063 (http://192.168.0.201:38893/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.core][INFO] 2020-11-24 04:06:50,598: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-24 04:06:50,641: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-24 04:06:50,661: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-24 04:06:50,693: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-24 04:06:50,746: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-24 04:06:50,766: signal_shutdown [signal-2]
[rospy.core][INFO] 2020-11-24 04:06:50,773: signal_shutdown [atexit]
