[rospy.client][INFO] 2020-11-11 03:20:28,658: init_node, name[/train_5526_1605064828653], pid[5526]
[xmlrpc][INFO] 2020-11-11 03:20:28,658: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-11-11 03:20:28,659: Started XML-RPC server [http://luigi:39971/]
[rospy.init][INFO] 2020-11-11 03:20:28,659: ROS Slave URI: [http://luigi:39971/]
[rospy.impl.masterslave][INFO] 2020-11-11 03:20:28,660: _ready: http://luigi:39971/
[rospy.registration][INFO] 2020-11-11 03:20:28,661: Registering with master node http://192.168.0.201:11311
[xmlrpc][INFO] 2020-11-11 03:20:28,661: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2020-11-11 03:20:28,760: registered with master
[rospy.rosout][INFO] 2020-11-11 03:20:28,760: initializing /rosout core topic
[rospy.rosout][INFO] 2020-11-11 03:20:28,764: connected to core topic /rosout
[rospy.simtime][INFO] 2020-11-11 03:20:28,766: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2020-11-11 03:20:28,788: topic[/odom] adding connection to [http://192.168.0.201:46537/], count 0
[rospy.internal][INFO] 2020-11-11 03:20:28,998: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2020-11-11 03:20:44,068: topic[/bev/flow_image] adding connection to [http://192.168.0.201:38315/], count 0
[rospy.internal][INFO] 2020-11-11 03:20:44,070: topic[/bev/occupancy_image] adding connection to [http://192.168.0.201:38315/], count 0
[rospy.core][INFO] 2020-11-11 03:20:46,740: signal_shutdown [atexit]
[rospy.internal][INFO] 2020-11-11 03:20:46,744: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-11-11 03:20:46,745: topic[/bev/flow_image] removing connection to http://192.168.0.201:38315/
[rospy.internal][INFO] 2020-11-11 03:20:46,745: topic[/bev/occupancy_image] removing connection to http://192.168.0.201:38315/
[rospy.internal][INFO] 2020-11-11 03:20:46,746: topic[/odom] removing connection to http://192.168.0.201:46537/
[rospy.impl.masterslave][INFO] 2020-11-11 03:20:46,746: atexit
[rospy.internal][ERROR] 2020-11-11 03:20:46,747: Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 732, in receive_once
    sock.setblocking(1)
OSError: [Errno 9] Bad file descriptor

[rospy.internal][WARNING] 2020-11-11 03:20:46,748: Unknown error initiating TCP/IP socket to 192.168.0.201:41223 (http://192.168.0.201:38315/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

